services:
  postgres:
    image: postgres:16
    container_name: campaign_buddy_postgres
    environment:
      POSTGRES_DB: campaign_buddy_ai
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data
    restart: unless-stopped

volumes:
  postgres_data:
